framework:
    messenger:
#        failure_transport: failed

        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
#             failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
             'App\Rates\Message\*': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
